spring:
  datasource:
    url: jdbc:mysql://localhost:3307/datav?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: 账号
    password: 密码
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      idle-timeout: 30000
      validation-timeout: 250
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
server:
  port: 3000

logging:
  file: logs/sys.log
  level:
    com.hmm.mht.bladevisual.dao: debug

file:
  upload:
    path: /data/bladevisual-ui/public/coverImg/
    baseUrl: coverImg/

mybatis-plus:
  global-config:
    id-type: ASSIGN_ID
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    banner: false